name       : ruby-listen
version    : 3.7.1
release    : 7
source     :
    - https://rubygems.org/downloads/listen-3.7.1.gem : 3b80caa7aa77fae836916c2f9e3fbcafbd15f5d695dd487c1f5b5e7e465efe29
homepage   : https://rubygems.org/gems/listen
license    : MIT
component  : programming.ruby
summary    : RubyGem - listen
description: |
    The Listen gem listens to file modifications and notifies you about the changes. Works everywhere!
builddeps  :
    - pkgconfig(ruby-3.1)
rundeps    :
    - ruby-rb-fsevent
    - ruby-rb-inotify
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc,extensions}
