name       : ruby-listen
version    : 3.1.5
release    : 4
source     :
    - https://rubygems.org/downloads/listen-3.1.5.gem : bd9ab5f1615a7e491a2251c09f0fae9407ab3bd7650bdb517dda54ec6cae6507
license    : MIT
component  : programming.ruby
summary    : RubyGem - listen
description: |
    The Listen gem listens to file modifications and notifies you about the changes. Works everywhere!
builddeps  :
    - pkgconfig(ruby-2.7)
rundeps    :
    - ruby-rb-fsevent
    - ruby-rb-inotify
    - ruby_dep
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc,extensions}
